# BioJS registry 

# CONTRIBUTING:
#   add your component to this file and make a pull-request. This'll add your component to the repo
#
#   it's written in TOML, which is basically ini files plus tags. Just copy
#   another component in this file and modify the tags/URLs etc to match your component
#   
#   Thanks for contributing! :) remember to tweet us and we'll let the world know

[biojs-io-clustal]

tags = ["client", "sequence", "recommended"]
  
  [[biojs-io-clustal.shields]]
  type = "build"
  img  = "https://drone.io/github.com/biojs/biojs-io-clustal/status.png"
  href = "https://drone.io/github.com/biojs/biojs-io-clustal/latest"

[biojs-io-fasta]

tags = ["client", "sequence", "fasta", "recommended"]

  [[biojs-io-fasta.shields]]
  type = "build"
  img  = "https://drone.io/github.com/biojs/biojs-io-fasta/status.png"
  href = "https://drone.io/github.com/biojs/biojs-io-fasta/latest"
  
  [[biojs-io-fasta.shields]]
  type = "tests"
  img = "http://img.shields.io/badge/coverage-75%-yellow.svg"
  href = "#"

  [[biojs-io-fasta.shields]]
  type = "doc"
  img = "http://img.shields.io/scrutinizer/g/filp/whoops.svg"
  href = "#"
  
[biojs-io-newick]

tags = ["client","newick","io","parser"]

[biojs-rest-ensembl]

tags = ["ensembl","rest"]
  
[biojs-rest-psicquic]

tags = ["client", "psicquic", "protein interaction"]

  [[biojs-rest-psicquic.shields]]
  type = "build"
  img  = "http://img.shields.io/badge/build-passing-brightgreen.svg"
  href = "#"
  
  [[biojs-rest-psicquic.shields]]
  type = "tests"
  img = "http://img.shields.io/badge/coverage-75%-yellow.svg"
  href = "#"

[biojs-vis-msa]

tags = ["client", "sequence", "msa", "recommended"]
  
  [[biojs-vis-msa.shields]]
  type = "build"
  img  = "https://drone.io/github.com/greenify/biojs-vis-msa/status.png"
  href = "https://drone.io/github.com/greenify/biojs-vis-msa/latest"
