# BioJS registry 

# CONTRIBUTING:
#   add your component to this file and make a pull-request. This'll add your component to the repo
#
#   it's written in TOML, which is basically ini files plus tags. Just copy
#   another component in this file and modify the tags/URLs etc to match your component
#   
#   Thanks for contributing! :) remember to tweet us and we'll let the world know

[biojs-io-clustal]

tags = ["client", "sequence", "recommended"]
  
  [[biojs-io-clustal.shields]]
  type = "build"
  img  = "https://drone.io/github.com/greenify/biojs-io-clustal/status.png"
  href = "https://drone.io/github.com/greenify/biojs-io-clustal/latest"

[biojs-io-fasta]

tags = ["client", "sequence", "fasta", "recommended"]

  [[biojs-io-fasta.shields]]
  type = "build"
  img  = "https://drone.io/github.com/greenify/biojs-io-fasta/status.png"
  href = "https://drone.io/github.com/greenify/biojs-io-fasta/latest"
  
  [[biojs-io-fasta.shields]]
  type = "tests"
  img = "https://codeclimate.com/github/greenify/biojs-vis-msa/badges/gpa.svg"
  href = "https://codeclimate.com/github/greenify/biojs-vis-msa"
  
[biojs-io-newick]

tags = ["client","newick","io","parser"]

[biojs-rest-ensembl]

tags = ["ensembl","rest"]

[biojs-vis-tooltip]

tags = ["tooltip","plugin"]
  
[biojs-rest-psicquic]

tags = ["client", "psicquic", "protein interaction"]

  [[biojs-rest-psicquic.shields]]
  type = "build"
  img  = "https://travis-ci.org/jmVillaveces/biojs-rest-psicquic.svg?branch=master"
  href = "https://travis-ci.org/jmVillaveces/biojs-rest-psicquic"
  
  [[biojs-rest-psicquic.shields]]
  type = "tests"
  img = "https://travis-ci.org/jmVillaveces/biojs-rest-psicquic.svg?branch=master"
  href = "https://travis-ci.org/jmVillaveces/biojs-rest-psicquic"

[biojs-vis-msa]

tags = ["client", "sequence", "msa", "recommended"]
  
  [[biojs-vis-msa.shields]]
  type = "build"
  img  = "https://drone.io/github.com/greenify/biojs-vis-msa/status.png"
  href = "https://drone.io/github.com/greenify/biojs-vis-msa/latest"


[biojs-legacy]

tags = ["legacy"]

[biojs-events]

tags = ["events"]

[biojs-model]

tags = ["models", "data", "objects"]

[biojs-vis-sequence]

tags = ["client", "sequence"]

[biojs-vis-easy_features]

tags = ["client", "features"]

  [[biojs-vis-easy_features.shields]]
  type = "build"
  img  = "https://drone.io/github.com/greenify/biojs-vis-easy_features/status.png"
  href = "https://drone.io/github.com/greenify/biojs-vis-easy_features/latest"

[biojs-rest-jsdas]

tags = ["bio", "das", "annotations"]

[biojs-vis-chromosome]

tags = ["div","chromosome","bands"]

[biojs-io-graduates]

tags = ["tutorial", "graduates", "parser"]

  [[biojs-io-graduates.shields]]
  type = "build"
  img  = "https://travis-ci.org/biojs/biojs-io-graduates.svg?branch=master"
  href = "https://travis-ci.org/biojs/biojs-io-graduates"
  
[biojs-io-snipspector]

tags = ["tutorial", "snippets", "parser"]

  [[biojs-io-snipspector.shields]]
  type = "build"
  img  = "https://travis-ci.org/biojs/biojs-io-snipspector.svg?branch=master"
  href = "https://travis-ci.org/biojs/biojs-io-snipspector"

[biojs-vis-pdbviewer]

tags = ["pdb", "protein", "structure"]
